### ISSUE TITLE
elm-cuke package on npm doesn't exist

### ISSUE THREAD

**Issue by trezona-lecomte** [genthaler/node-cucumber-elm-runner#1]
Hi there, I'm keen to write some cukes for my Elm code, but I haven't been able to get your cucumber-elm package running. The instructions for this repo say to do `npm install -g elm-cuke`, however this fails with `npm ERR! Cannot read property 'path' of null`. This is likely because the package doesn't actually exist: 
```
$ npm search elm-cuke
No matches found for "elm-cuke"
```
If this is still in progress that's understandable, perhaps you could update the README to reflect this? Also, if I can help at all let me know.

Thanks!

**Comment by genthaler** [comment]
You're absolutely right, this is a work in progress. I didn't think it'd take this long, but summer hit and I've had no time. The node-test-runner code I'd been using as a basis has been changing a lot too, I'd wanted to make the two as similar a user experience as possible. As for help, it's not in a state to share in any sense, feel free to write something to get going. The cucumber-elm code is about 90% feature complete, so that should be good to go. I've annotated the README as suggested.

**Comment by trezona-lecomte** [comment]
Hey, thanks for the quick reply and the clarification. I'll keep an eye on this and work something out in the meantime. Appreciate your effort!
